<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.KomTheme</RootNamespace>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.KomTheme</PackageId>
    <Description>Core KomTheme package - options, layouts, and style definitions for Sufi Platform.</Description>
  </PropertyGroup>


  <!--<ItemGroup >
    <PackageReference Include="SufiChain.SufiAbp.UI.Abstractions" Version="$(SufiAbpVersion)" />
  </ItemGroup>-->


  <ItemGroup Condition="'$(UseSufiAbpProjectReferences)' == 'true'">
    <ProjectReference Include="..\..\..\..\sufi-abp\framework\SufiChain.SufiAbp.UI.Abstractions\SufiChain.SufiAbp.UI.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseSufiAbpProjectReferences)' != 'true'">
    <PackageReference Include="SufiChain.SufiAbp.UI.Abstractions" Version="$(SufiAbpVersion)" />
  </ItemGroup>



</Project>
