<Project>
  <Import Project="versions.props" />
  <PropertyGroup>
    <NuGetAudit>false</NuGetAudit>
    <NoWarn>$(NoWarn);CS8601;CS8602;CS8603;CS8604;CS8613;CS8618;CS8619;CS8620;CS8625;CS8629;CS8632;CS8669;CS8609;CS8767</NoWarn>

    <UseSufiAbpProjectReferences>false</UseSufiAbpProjectReferences>
    <!--<UseSufiAbpProjectReferences Condition="'$(UseSufiAbpProjectReferences)' == '' And Exists('$(MSBuildThisFileDirectory)..\..\sufi-abp\framework\SufiChain.SufiAbp.Core\SufiChain.SufiAbp.Core.csproj')">true</UseSufiAbpProjectReferences>
    <UseSufiAbpProjectReferences Condition="'$(UseSufiAbpProjectReferences)' == ''">false</UseSufiAbpProjectReferences>-->
  </PropertyGroup>

  <PropertyGroup>
    <Company>Sufi Chain Intelligent Solutions</Company>
    <Authors>SufiChain Team</Authors>
    <Product>SufiTheme</Product>
    <PackageProjectUrl>https://sabp.ir</PackageProjectUrl>
    <RepositoryUrl>https://git.sabp.ir/sufi-chain/sufi-theme.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon Condition="Exists('$(MSBuildThisFileDirectory)icon.png')">icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup Condition="Exists('$(MSBuildThisFileDirectory)icon.png')">
    <None Include="$(MSBuildThisFileDirectory)icon.png" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

</Project>
