<Project>

  <PropertyGroup>
    <SufiVersion>0.1.0-alpha.2.0.0</SufiVersion>
    <SufiThemeVersion>0.1.0-alpha.2.0.0</SufiThemeVersion>
    <LangVersion>latest</LangVersion>
    <AbpVersion>10.6.1</AbpVersion>
    <SufiAbpVersion>0.1.0-alpha.1.0</SufiAbpVersion>
    <MicrosoftAspNetCoreComponentsAuthorizationVersion>10.0.9</MicrosoftAspNetCoreComponentsAuthorizationVersion>
    <MicrosoftAspNetCoreComponentsWebVersion>10.0.9</MicrosoftAspNetCoreComponentsWebVersion>
    <MicrosoftAspNetCoreComponentsWebAssemblyVersion>10.0.9</MicrosoftAspNetCoreComponentsWebAssemblyVersion>
  </PropertyGroup>

</Project>
