<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SufiChain.KomTheme.Blazor.WebAssembly</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <IsPackable>true</IsPackable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.KomTheme.Blazor.WebAssembly</PackageId>
    <Description>KomTheme Blazor WebAssembly components and layouts for Sufi Platform.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="$(MicrosoftAspNetCoreComponentsWebAssemblyVersion)" />
  </ItemGroup>

  <!--<ItemGroup>
    <ProjectReference Include="..\..\..\..\sufi-abp\framework\SufiChain.SufiAbp.UI.Blazor.WebAssembly\SufiChain.SufiAbp.UI.Blazor.WebAssembly.csproj"  />
  </ItemGroup>-->

  <ItemGroup>
    <PackageReference Include="SufiChain.SufiAbp.UI.Blazor.WebAssembly" Version="$(SufiAbpVersion)"/>
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\SufiChain.KomTheme.Blazor\SufiChain.KomTheme.Blazor.csproj" />
    <ProjectReference Include="..\SufiChain.KomTheme.Blazor.WebAssembly.Bundling\SufiChain.KomTheme.Blazor.WebAssembly.Bundling.csproj" />
  </ItemGroup>

</Project>
