<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.KomTheme.Blazor</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <IsPackable>true</IsPackable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.KomTheme.Blazor</PackageId>
    <Description>KomTheme Blazor layouts and components for Sufi Platform.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SufiChain.SufiAbp.Core" Version="1.0.0-alpha.1.0" />
    <PackageReference Include="SufiChain.SufiAbp.Security" Version="1.0.0-alpha.1.0" />
    <PackageReference Include="SufiChain.SufiAbp.UI.Blazor" Version="1.0.0-alpha.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.2" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.KomTheme\SufiChain.KomTheme.csproj" />

  </ItemGroup>

</Project>
