<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.KomTheme.Blazor</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <IsPackable>true</IsPackable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.KomTheme.Blazor</PackageId>
    <Description>KomTheme Blazor layouts and components for Sufi Platform.</Description>
  </PropertyGroup>


  <!--<ItemGroup>
    <PackageReference Include="SufiChain.SufiAbp.Core" Version="$(SufiAbpVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.Security" Version="$(SufiAbpVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.UI.Blazor" Version="$(SufiAbpVersion)" />
  </ItemGroup>-->

  <ItemGroup Condition="'$(UseSufiAbpProjectReferences)' == 'true'">
    <ProjectReference Include="..\..\..\..\sufi-abp\framework\SufiChain.SufiAbp.Core\SufiChain.SufiAbp.Core.csproj" />
    <ProjectReference Include="..\..\..\..\sufi-abp\framework\SufiChain.SufiAbp.Security\SufiChain.SufiAbp.Security.csproj" />
    <ProjectReference Include="..\..\..\..\sufi-abp\framework\SufiChain.SufiAbp.UI.Blazor\SufiChain.SufiAbp.UI.Blazor.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseSufiAbpProjectReferences)' != 'true'">
    <PackageReference Include="SufiChain.SufiAbp.Core" Version="$(SufiAbpVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.Security" Version="$(SufiAbpVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.UI.Blazor" Version="$(SufiAbpVersion)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="$(MicrosoftAspNetCoreComponentsWebVersion)" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="$(MicrosoftAspNetCoreComponentsAuthorizationVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.KomTheme\SufiChain.KomTheme.csproj" />


  </ItemGroup>

</Project>
